### ISSUE TITLE
404 No such route or hostname

### ISSUE THREAD

**Issue by orlovk** [TinkoffCreditSystems/invest-openapi-java-sdk#1]
Привет!
Хотелось подергать API-шку, но все попытки упираются вот во что:
```
404 Not Found
No such route or hostname
```
Это у меня не работает или у вас?

**Comment by orlovk** [comment]
Я все же что-то, видимо не так делаю еще, пример на go, который в документации так и не взлетел. Поменял на post, убрал лишний /
Что вот эта строка означает:
`Authorization: Bearer {TOKEN}`
Это значит, что токен должен быть вот таким: Bearer t.yhkKD...

Ответ все еще 404, что несколько сбивает с толку, мне кажется логично было бы код ошибки возвращать.

**Comment by Luchanso** [comment]
У меня со страницы документации (свагера) всё работает

**Comment by Luchanso** [comment]
@orlovk пример cURL запроса у меня:
```
curl -X GET "https://api-invest.tinkoff.ru/openapi/sandbox/market/stocks" -H "accept: application/json" -H "Authorization: Bearer t.4HIAHktnQ-nfkX5lgy7ZBYeLdcZ4zMNASD24123NSa3L9NHm-5wdQzBK_Kh_vGwv8NGET055F9bMXh7SDsWBA"
```

**Comment by orlovk** [comment]
@Luchanso, сейчас документацию поправили, изначально не было два раза sandbox.

на всякий случай оставлю код на питоне, может кому пригодится:
```
import requests as r
import json

TOKEN_sandox = ''
headers_sandbox = {'Authorization': f'Bearer {TOKEN_sandox}'}
print(f'headers_sandbox={headers_sandbox}')


ret = r.post('https://api-invest.tinkoff.ru/openapi/sandbox/sandbox/register', headers=headers_sandbox)
print(f'headers={ret.headers}\n')
print(f'content={ret.content}\n')
json_data = json.loads(ret.content, encoding='asci')
print(f'json_data={json_data}\n')
```
