### ISSUE TITLE
Unexpected status line: 429 Too Many Requests

### ISSUE THREAD

**Issue by ityulkanov** [TinkoffCreditSystems/invest-openapi-java-sdk#101]
Every time I'm calling the API I'm get spammed with these messages all over my console. I've tried to call initCleanupProcedure(api); right after getting the results of a call, but no luck. Can anyone explain what do I do wrong with the api? I can't work with it properly, becase after one single request It simply stuck into that mode where I can't get any more info from the API and I have to start my app all over again.

**Comment by NikitaMelnikov** [comment]
We are using rate limiting, so 429 status is correct
https://tinkoffcreditsystems.github.io/invest-openapi/rest/

**Comment by ityulkanov** [comment]
I know about limits, but I don't understand what should I do to make my app work without these 429s. Or it is unavoidable?
