### ISSUE TITLE
Некорректные данные в StreamingEvent.Orderbook

### ISSUE THREAD

**Issue by sergey-klochkov** [TinkoffCreditSystems/invest-openapi-java-sdk#102]
Некорректные данные приходят в StreamingEvent.Orderbook.
Для тикера HWM смотрю стакан в терминале и дебагером данные, которые приходят через StreamingEvent.Orderbook.
В терминале лучший аск 17.99 через StreamingEvent.Orderbook несколько минут подряд прилетают апдейты с аском 17.95

Такое же поведение сегодня замечал в тикерах LITE, LEVI, GS

Разве данные в стакане терминала и то, что отдается в стриминг-апи не должно совпадать?

**Comment by zlumyo** [comment]
Вопрос скорее к самому API, чем к SDK - лучше задать его [там](https://github.com/TinkoffCreditSystems/invest-openapi/issues).
Не исключаю, что это может быть в реализации StreamingContext, но в процессе диагностики не я не нашёл этому подтверждения. Тикет пока закрываю.
