### ISSUE TITLE
Получение информации о позициях в песочнице

### ISSUE THREAD

**Issue by MrSwimmer** [TinkoffCreditSystems/invest-openapi-java-sdk#104]
Ребята, я что-то не могу найти методы (в свагере тоже) для получения информации о позициях в песочнице, вот типа я выставил себе позиции в песочнице, а посмотреть их как я могу? Или песочница не так работает?

**Comment by zlumyo** [comment]
Песочница работает не совсем так.
Когда вы используете токен от песочницы, то метод [GET /portfolio](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/portfolio/get_portfolio) начинает возвращать не ваш реальный портфель, а "песочный". Аналогично со всеми другими методами - использование "песочного" токена не влияет на _реальные_ деньги/активы.
