### ISSUE TITLE
С Open Api возвращается некорректное значение quantity для некоторых операций.

### ISSUE THREAD

**Issue by kobylyanets** [TinkoffCreditSystems/invest-openapi-java-sdk#107]
Делаю программу для статистики. Заметил, что общее число купленных бумаг отличается от проданных. Позиции закрыты. 

Стал копать и нашел, что для некоторых операций по бумагам возвращается неверное количество.
![photo_2020-11-15_00-01-52](https://user-images.githubusercontent.com/16237193/99157063-0c3bc580-26d7-11eb-853c-6a9ab8053365.jpg)
<img width="678" alt="Снимок экрана 2020-11-15 в 00 10 00" src="https://user-images.githubusercontent.com/16237193/99157065-0e9e1f80-26d7-11eb-85c1-27cd70142a3b.png">
На скринах одна из таких операций. В истории операций брокерского счета верное количество - 3. OpenApi возвращает - 22.

**Comment by AlexanderVolkovTCS** [comment]
Вероятно, quantity = 22 и quantityExecuted = 3,
т.е. вы выставили 22 заявки, но исполнилось только 3. 
Проверьте, пожалуйста.  Ориентироваться надо на quantityExecuted.
