### ISSUE TITLE
429 Too Many Requests при простой инициализации клиента

### ISSUE THREAD

**Issue by stalexxx** [TinkoffCreditSystems/invest-openapi-java-sdk#109]
При инициализации происходит многократно (для разных клиентов)

> ноя 18, 2020 2:21:00 AM ru.tinkoff.invest.openapi.okhttp.StreamingContextImpl$StreamingApiListener onFailure
> SEVERE: Что-то произошло в Streaming API клиенте #6
> java.net.ProtocolException: Expected HTTP 101 response but was '429 Too Many Requests'
> 	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:185)
> 	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:156)
> 	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:140)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Лечится путем уменьшения параллелизма, то есть подпихиванием пролеченной копией конфиг файл в свой classpath. Это сделано специально?

**Comment by stalexxx** [comment]
upd
это происходит при повторной инициализаци клиента. Мне кажется, сообщение об ошибке должно быть другим

**Comment by zlumyo** [comment]
Конфигурация по умолчанию настроена так, что при инициализации одного клиента сразу создаётся максимально доступное количество соединений - 6 ([согласно документации](https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/)).
Соответственно, если необходимо это изменить, то придётся изменить конфиг.
