### ISSUE TITLE
Добавить sdk в репозиторий

### ISSUE THREAD

**Issue by DonKeyHot1** [TinkoffCreditSystems/invest-openapi-java-sdk#11]
Было бы здорово, если sdk появился в публичных репозиториях maven/gradle, чтобы не приходилось подкладывать jar'ник вручную.

**Comment by NikitaMelnikov** [comment]
Привет, мы в процессе, ждём аппрува от мейнтейнеров мавен ментрал

**Comment by DonKeyHot1** [comment]
Круто!
