### ISSUE TITLE
Каракули в документации и в swagger

### ISSUE THREAD

**Issue by skarpushin** [TinkoffCreditSystems/invest-openapi-java-sdk#111]
При открытии свагера все комментарии каракулями
![image](https://user-images.githubusercontent.com/4069181/100387992-72f7a200-303a-11eb-832a-edfb26604357.png)

Тоже самое при переходе на исходники в IDE
![image](https://user-images.githubusercontent.com/4069181/100388022-860a7200-303a-11eb-8339-9cf2d2ab8c8f.png)

**Comment by AlexanderVolkovTCS** [comment]
В интерфейсе сваггера , в notepad++ и при загрузке в visual code проблем нет: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/

В вашем IDE можно изменить кодировку вручную?

**Comment by skarpushin** [comment]
**Браузер = Chrome** -- в нём я не нашёл как поменять кодировку. Да и как-то прошлый век это уже. Предполагается, что через HTTP Header "Content-Type" сервер сразу сообщает корректную кодировку клиенту. 
Сейчас там `content-type: text/yaml` а должно быть `content-type: text/yaml; charset=utf-8`

**IDE = Eclipse**. Не знаю, где там это настроить, За уже 12 лет работы на Java, ещё ни разу не встрчал комментарии на русском :-) Да и главное -- хотелось бы, чтобы работало из коробк.

**Comment by zlumyo** [comment]
Провёл эксперимент.
Открыл файл в браузере https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/swagger.yaml
Сохранил (Ctrl+S).
Открыл в редакторе (например VScode). Редактор говорит, что файл в кодировке UTF-8. Каракуль нет. Никаких дополнительных действий не производил.
Соглсен, что `charset=utf-8` стоит поставить, но это уже вопрос не к SDK, а [к документации API](https://github.com/TinkoffCreditSystems/invest-openapi/issues).

**Comment by zlumyo** [comment]
Ещё раз всё проверил.
Оригинал файла в репозитории хранится в UTF-8. Мы хостимся в GithubPages. Он ожидает, что файлы будут в UTF-8, а потому не производит никаких манипуляций - отдаёт всё как есть. Посему механизмов модифицировать хедеры не предоставляется.
Судя по скриншотам, мы имеем дело с Windows. Увы, такие проблемы там могут возникать. С нашей стороны мы вряд ли что-то можем сделать.
