### ISSUE TITLE
Некорректные значения open/closing price у тикера TECH(figi=BBG000C15114)

### ISSUE THREAD

**Issue by alexeyvip** [TinkoffCreditSystems/invest-openapi-java-sdk#113]
Странно, но у тикера TECH(figi=BBG000C15114) приходят некорректные значения.
Пример:
_open_price=321.66
closing_price=321.67_
Мой баланс по этому тикеру равен 1150, умножаю и получаю 369909 USD, хотя должно быть примерно 110 USD

По всем остальным тикерам всё ок, к примеру если взять TBIO(figi=TCS00A102EK1) то:
_open_price=0.0965
closing_price=0.0965
balance=300_
Считаем 300*0.0965=28.95 USD - корректно

Проблема только с тикером TECH.
**Боевая среда.**
Значения open/close price беру после подписки на свечи.

**Comment by AlexanderVolkovTCS** [comment]
Добрый вечер, торговля TECH через API вообще запрещена:
https://tinkoffcreditsystems.github.io/invest-openapi/
