### ISSUE TITLE
Поиск описания ошибки по TrackingID

### ISSUE THREAD

**Issue by OlegShalagin** [TinkoffCreditSystems/invest-openapi-java-sdk#114]
Привет!

При попытке выставить ордер получил следующее сообщение: `Ошибка при исполнении запроса, trackingId = 0f517bc72fa97bfb`. 4 из 4 попыток завершились ошибкой.
Где можно посмотреть описание произошедшего по этому Id ?

**Comment by zlumyo** [comment]
Добрый день! Это внутренний идентификатор, по которому поддержка может найти необходимую информацию. Самостоятельно вы ничего с ним не можете сделать.

**Comment by OlegShalagin** [comment]
@zlumyo Поддержка в чате приложения Инвестиции? Там не осветили на этот вопрос. Или спросить еще раз?

**Comment by zlumyo** [comment]
Да, из чата Инвестиций. А более подробные тексты ошибок уже завист не от SDK, а от самого API. Можете задать вопрос [там](https://github.com/TinkoffCreditSystems/invest-openapi/issues).
