### ISSUE TITLE
Обновления на Maven Cental

### ISSUE THREAD

**Issue by OlegShalagin** [TinkoffCreditSystems/invest-openapi-java-sdk#115]
Привет!

Планируются ли новые релизы SDK ?

**Comment by krylovsergey1999** [comment]
А не планируется создание чата в телеграме для java разрабов. Чтобы можно было собрать сообщество и нормально общаться.

**Comment by zlumyo** [comment]
Новые релизы планируются. В частности, следующий ожидается в феврале.
Отдельного чата для Java-разработчиков не планируется - большого запроса от людей не наблюдаем. Но, разумеется, частную инициативу приветствуем.

**Comment by OlegShalagin** [comment]
@zlumyo, спасибо! Ждем-с)
