### ISSUE TITLE
Maven central artifacts v0.5 are not usable

### ISSUE THREAD

**Issue by fedorov-s-n** [TinkoffCreditSystems/invest-openapi-java-sdk#126]
Версия 0.5 залита не полностью. Вот этого артефакта не хватает:

```
<parent>
    <groupId>ru.tinkoff.invest</groupId>
    <artifactId>openapi-java-sdk</artifactId>
    <version>0.5</version>
</parent>
```

По этой причине зависимость не получается использовать в maven. С версией 0.4.1 все в порядке.

**Comment by Dimantchick** [comment]
Постараюсь не забыть из дома скинуть свой pom. Тоже была такая проблема, но не помню, что сделал и все ок.

**Comment by SavchenkoVV** [comment]
Родительский артефакт не openapi-java-sdk, а openapi-java-sdk-java8

**Comment by zlumyo** [comment]
`openapi-java-sdk` - это корневой артефакт, который ссылается на все компоненты:

- core (соответственно openapi-java-sdk-core)
- java8
- example

При подготовке версии 0.5 было решено отказаться от публикации корневого артефакта. example нужен не всем, а при импорте java8 пакет core подтягивается автоматически.
Если это всё таки нужно, то можем отказаться от такой практики в дальгейшем.

**Comment by Kirill-mol** [comment]
Так и не понял, почему версию 0.4.1 можно просто подключить через maven добавлением зависимости 
```xml
<dependency>
        <groupId>ru.tinkoff.invest</groupId>
	<artifactId>openapi-java-sdk-java8</artifactId>
	<version>0.4.1</version>
</dependency>
```
А версию 0.5 можно

**Comment by fedorov-s-n** [comment]
Ок, давайте подробнее, похоже, я плохо объяснил.

Я подключаю зависимость в мавен:
```
        <dependency>
            <groupId>ru.tinkoff.invest</groupId>
            <artifactId>openapi-java-sdk-java8</artifactId>
            <version>0.4.1</version>
        </dependency>
```
И вуаля, все работает.

Теперь подключим более новую версию.
```
        <dependency>
            <groupId>ru.tinkoff.invest</groupId>
            <artifactId>openapi-java-sdk-java8</artifactId>
            <version>0.5</version>
        </dependency>
```
`mvn install` и вылезает ошибка.

> Failed to collect dependencies at ru.tinkoff.invest:openapi-java-sdk-java8:jar:0.5: Failed to read artifact descriptor for ru.tinkoff.invest:openapi-java-sdk-java8:jar:0.5: Could not find artifact ru.tinkoff.invest:openapi-java-sdk:pom:0.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

Почему она вылезает? Как я  понимаю, потому что артефакта ru.tinkoff.invest:openapi-java-sdk:pom:0.5 нет в репозитории.
Проверим: https://repo1.maven.org/maven2/ru/tinkoff/invest/openapi-java-sdk/
Действительно, нет.

> Родительский артефакт не openapi-java-sdk, а openapi-java-sdk-java8

В https://repo1.maven.org/maven2/ru/tinkoff/invest/openapi-java-sdk-java8/0.5/openapi-java-sdk-java8-0.5.pom написано:
```
<parent>
    <groupId>ru.tinkoff.invest</groupId>
    <artifactId>openapi-java-sdk</artifactId>
    <version>0.5</version>
</parent>
```
Это, в моем понимании, и не дает пользоваться версией 0.5. Поправьте, если я в чем-то неправ.

Компонент example (мне лично) не нужен, нужно, чтобы зависимость подтягивалась.

**Comment by Dimantchick** [comment]
Вот как раз у компа уведомление увидел.
Вот мой пом
```
<modelVersion>4.0.0</modelVersion>

    <groupId>TinkoffInvest</groupId>
    <artifactId>Test0.5</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.3</version>
                    <configuration>
                        <source>1.11</source>
                        <target>1.11</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
        <groupId>com.github.TinkoffCreditSystems.invest-openapi-java-sdk</groupId>
        <artifactId>openapi-java-sdk-core</artifactId>
        <version>v0.5</version>
    </dependency>
        <dependency>
            <groupId>com.github.TinkoffCreditSystems.invest-openapi-java-sdk</groupId>
            <artifactId>openapi-java-sdk-java8</artifactId>
            <version>v0.5</version>
        </dependency>
        <dependency>
            <groupId>com.github.TinkoffCreditSystems.invest-openapi-java-sdk</groupId>
            <artifactId>openapi-java-sdk-example</artifactId>
            <version>v0.5</version>
        </dependency>
        <dependency>
            <groupId>org.sf.teachingbox</groupId>
            <artifactId>teachingbox-core</artifactId>
            <version>1.2.3</version>
        </dependency>
    </dependencies>
```

В моем случае все собралось с таким помом.

**Comment by reaxio** [comment]
Итак, проблема идентифицирована, есть ли какой-то ориентировочный срок по фиксу?

**Comment by zlumyo** [comment]
Фикс готов. Нужно перейти на версию 0.5.1
(Прошу прощения за такой долгий срок)
