### ISSUE TITLE
Добавить выгрузки информации по портфелю

### ISSUE THREAD

**Issue by vananiev** [TinkoffCreditSystems/invest-openapi-java-sdk#127]
Было бы хорошо, если бы  документацию были добавлены примеры по выгрузке следующей информации о портфеле:
1. Свойства портфеля: стоимость активов (руб), курсы валют ЦБ (если есть)
1. Позиции по денежным средствам портфеля в разбивке по площадкам (фондовый, срочный, валютный, спб рынки)
1. История ввода/вывода денежных средств, а также перевода с/на другой счет
1. Список ценных бумаг портфеля с фондового рынка
1. Транзакции на фондовом рынке
1. Выплата дивидендов по акциям
1. Выплата купонов, амортизации и погашения облигаций
1. Транзакции на срочном рынке по фьючерсам и опционам (купля, продажа, экспирация)
1. Перечисления вариационной маржи по сделкам срочного рынка с указанием контракта, по которому выполнено начисление
1. Транзакции на валютном рынке
1. Ввод и вывод ценных бумаг с брокерского счета
1. Конвертация ценных бумаг
1. Удержания налога
1. Котировки ЦБ

**Comment by AlexanderVolkovTCS** [comment]
Добрый день,
1, 2 и 4 - реализуется в getPortfolio
3, 5, 6, 7,10, 11 и 13 - в getOperations
Фьючерсы - пока не поддерживаются, курсы валют ЦБ - тоже, но вместо ЦБ можете использовать котировки валют на бирже.

**Comment by vananiev** [comment]
Есть какие-то изменения по п. 8, 9, 12?
