### ISSUE TITLE
Добавить тестовый кабинет и токен

### ISSUE THREAD

**Issue by vananiev** [TinkoffCreditSystems/invest-openapi-java-sdk#128]
Было бы хорошо разработчикам клиентов иметь тестовый кабинет и токен на RO операции.

**Comment by Dimantchick** [comment]
Если я правильно вас понял, то вас интересуют токены с разграниченными правами (только чтение например).
Если так, то данный проект лишь реализует апи на языке ява и не может дать функционал, которого в нем нет.
Обратитесь сюда https://github.com/TinkoffCreditSystems/invest-openapi/issues - это основной репозиторий апи. По токенам с разграниченными правами таск есть. Да там много всего есть, что запланировано неопределенно когда.

**Comment by vananiev** [comment]
Запрашивал параметры для авторизации при тестирования приложения. Эти параметры должны быть доступны всем разработчикам. Например: логин-пароль = demo:demo или это может быть токен или еще что-то.

**Comment by zlumyo** [comment]
Это одна из первых issue на странице [проекта самого API](https://github.com/TinkoffCreditSystems/invest-openapi/issues/12). Конкретно вашей формулировки там нет, но если и задавать вопросы по этой теме, то именно там.
