### ISSUE TITLE
Не приходит рублевой баланс портфеля

### ISSUE THREAD

**Issue by Kain-evil** [TinkoffCreditSystems/invest-openapi-java-sdk#130]
Здравствуйте!
При запросе текущих позиций портфеля игнорируется получение рублевого баланса и фьючерсов. 
`for (PortfolioPosition x : account.getPortfolio().getPositions()) {
System.out.println(x.getName())}`
Отображаются все позиции, кроме рублей и фьючерсов.
 Есть какой-либо прямой или обходной способ их получить?
Заранее благодарю!

**Comment by Kain-evil** [comment]
Все, разобрался в причинах. Рублевой баланс (да и все вообще валютные балансы) забит в объект CurrencyPosition. Однако сразу возникает противоречие - почему тогда он отсутствует в объекте PortfolioPosition (валютные балансы же присутствуют в нем - все, кроме рублевого).
По фьючерсам вопрос открытый.

**Comment by zlumyo** [comment]
Фьючерсы пока не поддерживаются самим API, тут силами SDK ничего не сделаешь. Данный вопрос уже поднят на странице самого [проекта API](https://github.com/TinkoffCreditSystems/invest-openapi/issues/501).
