### ISSUE TITLE
Futures And ETFs

### ISSUE THREAD

**Issue by g-sg-v** [TinkoffCreditSystems/invest-openapi-java-sdk#134]
Не приходят фьютчерсы и внебиржевые ETF'ы через API. Планируется ли поддержка?

**Comment by zlumyo** [comment]
Внебиржевая торговля сейчас полностью вне возможностей API. Торговля фьючерсами пока тоже недоступна, но в разработке. Как только это станет возможным, SDK адаптируется к новым возможностям. Подробности по данному вопросу можно узнать на странице самого [проекта API](https://github.com/TinkoffCreditSystems/invest-openapi).
