### ISSUE TITLE
Брокерские счета

### ISSUE THREAD

**Issue by Dimantchick** [TinkoffCreditSystems/invest-openapi-java-sdk#135]
Недавно появилась возможность создавать несколько брокерских счетов. Счет открыл, но через апи доступ получить не могу.
Если запрашиваю через getUserContext().getAccounts(), то получаю счета Tinkoff и TinkoffIis.
Пробовал подбрасывать ид вручную из ссылки https://www.tinkoff.ru/invest/portfolio/[набор цифр]/, но не принимает, что ожидаемо.

Это нормальное поведение, баг или поддержка просто еще не реализована в апи?

**Comment by zlumyo** [comment]
Это нормальное поведение для API в данный момент времени, потому что эта функциональность ещё не реализована. Для ясности: SDK тут точно не причём. Подробности по данному вопросу можно узнать на странице самого [проекта API](https://github.com/TinkoffCreditSystems/invest-openapi).
