### ISSUE TITLE
Приходят ошибочные цены свеч при подписке на StreamingEvent.Candle

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi-java-sdk#138]
В 2021-08-04 15:18:05,013 по UTC (2021-08-04 18:18:05,013 по МСК) наблюдал такую картину по тикету 'NVDA' прилетела цена закрытия равная 199.94$. Если потом обратиться к историческим свечам за это время, то данной цены даже и рядом не было. В этом интервале минимальная цена за 2021-08-04 15:15:00 равна 201.4$ за 2021-08-04 15:20:00 равна 200.79$.

Как бы не совсем понятно откуда такая цена? Может ли это быть баг?

**Comment by zlumyo** [comment]
Практически наврняка я могу сказать, что дело не в SDK, т.к. оно всего лишь парсит приходящие данные. Думаю с подобным вопросом стоит обратиться в [главный репозиторий openapi](https://github.com/TinkoffCreditSystems/invest-openapi).
