### ISSUE TITLE
Как работать с LimitOrder

### ISSUE THREAD

**Issue by Freeongoo** [TinkoffCreditSystems/invest-openapi-java-sdk#141]
Не совсем понимаю как работать с LimitOrder.

После того как был открыт LimitOrder через api.getOrdersContext().placeLimitOrder
1. Как понять, когда наш лимитный ордер отработал? То есть открылась поизиция при достижении указанной цены
2. Насколько я понял при получении List(PortfolioPosition) через apiConnectKeeper.getApi().getPortfolioContext() там будут как обычные рыночные заявки, которые уже открыли, так и лимитные ордеры. Вопрос в то, как отличить лимитные PortfolioPosition от рыночных?

**Comment by Freeongoo** [comment]
@zlumyo после открытия лимитной заявки, получаю список getOrders - возвращает пустоту. Хотя лимитная заявка выполнилась успешно

**Comment by zlumyo** [comment]
Выполнилась или выставилась? Если второе, то тут скорее претензии как самому API нежели к SDK. Если первое, то getOrders не для этого - он возвращает только выставленные. Выполненные можно получить у метода getOperations. К сожалению, объекты Operation не содержать поля orderId, поэтому соотнести выставленные заявки придётся по косвенным признакам.
Сейчас активно ведётся работа над новой версией API (для которой соответственно будет новый SDK). Там это упущение исправят.

**Comment by vigorious78** [comment]
"...Сейчас активно ведётся работа над новой версией API.." 
А есть приблизительные сроки, когда будет версия, которую можно попробовать ?

**Comment by Freeongoo** [comment]
@zlumyo а разве нельзя использовать Operation.id для соотношения с orderId?
