### ISSUE TITLE
Websocket Подписка на все бумаги

### ISSUE THREAD

**Issue by leodev87** [TinkoffCreditSystems/invest-openapi-java-sdk#142]
Как подписаться сразу на все тикеры? 
В цикле получаю Ту мэни реквестс.

**Comment by AlexanderVolkovTCS** [comment]
Соединение по сокетам разрывается, если клиент не успевает забирать данные, скорее всего подписаться сразу на все инструменты и не получится.

Допускается до 6ти одновременных соединений по вебсокетам: попробуйте равномерно по ним распределить подписки.
