### ISSUE TITLE
[SEVERE ] Что-то пошло не так в подписке на стрим StreamingEvent. 

### ISSUE THREAD

**Issue by icewind666** [TinkoffCreditSystems/invest-openapi-java-sdk#15]
[2019-09-23 19:04:46] [SEVERE ] Что-то пошло не так в подписке на стрим StreamingEvent. 

замечено что такая ошибка появляется при не очень стабильном интернете (возможно из-за таймаутов...).
Хотя может и не связано с этим...

Очень хотелось бы может что-нибудь по подробнее в ошибке..

Появляется редко - раньше было гораздно чаще (до версии 0.2)

**Comment by icewind666** [comment]
при этом - всегда сначала у меня успешно размещается заявка 
и после этого сразу эта ошибка...

одиночно или в каких то других сценариях - не появляется

**Comment by icewind666** [comment]
UPDATE.
и в другом сценарии повторилось сейчас.

[2019-09-24 10:25:27] [FINE   ] Изменился торговый статус инструмента: normal_trading
[2019-09-24 10:25:27] [SEVERE ] Что-то пошло не так в подписке на стрим StreamingEvent.

**Comment by icewind666** [comment]
@NikitaMelnikov в общем этот issue наверное можно закрыть.
Я нашел в чем дело - у меня внутри стратегии был exception. 

Но сейчас он так маскируется что на выходе "Что-то пошло не так в подписке на стрим StreamingEvent" получается ))) а по факту у меня там внутри null pointer exception был в одном месте))

Обернул все свое в свои try-catch чтобы ничего наверх не летело - и все стало ОК.

**Comment by NikitaMelnikov** [comment]
Думаю надо подумать как справляться с нестабильным соединением внутри SDK. 
Как идея - добавить Backoff для обработки потери соединения
@zlumyo что думаешь?

**Comment by zlumyo** [comment]
Да, идея интересная. Соорудим к 0.3 
Плюс, думаю поменять немного формат логгирования с тем, чтобы при печати ошибочных ситуаций показывать непосредственно текст ошибок - так должно стать проще выявлять причины.

**Comment by NikitaMelnikov** [comment]
@zlumyo заведешь отдельные таски и эту закроем?

**Comment by zlumyo** [comment]
Завёл отдельный задачи
