### ISSUE TITLE
"Что-то пошло не так в подписке на стрим StreamingEvent."

### ISSUE THREAD

**Issue by icewind666** [TinkoffCreditSystems/invest-openapi-java-sdk#3]
2019-09-13 13:19:55] [SEVERE ] Что-то пошло не так в подписке на стрим StreamingEvent.

Собственно, это сообщение теперь всегда) в примере из sdk для java.
Хотя работало сегодня утром.

Может тех работы ведутся сейчас какие-то ?

**Comment by orlovk** [comment]
У меня то же самое -- поработало немного и теперь вот эта же ошибка.
Кстати, корректный url вот такой
https://api-invest.tinkoff.ru/openapi/sandbox/sandbox/register
там два раза sandbox!
апишка не просто сырая, она в стадии development еще)

**Comment by icewind666** [comment]
ожило) причины неизвестны)

**Comment by NikitaMelnikov** [comment]
> Кстати, корректный url вот такой

А где другой написан?

**Comment by NikitaMelnikov** [comment]
В логах не осталось trackingId или исключения?

**Comment by icewind666** [comment]
к сожалению нет. в логах только то сообщение которое выше писал..
причем я в коде вижу что там и throwable есть, но он почему то не долетел. 

Либо в логере не печатается...

@Override
        public void onError(Throwable throwable) {
            logger.log(Level.SEVERE, "Что-то пошло не так в подписке на стрим StreamingEvent.", throwable);
        }

**Comment by icewind666** [comment]
а вот сейчас проскочило один раз - исключение было 
java.util.concurrent.CompletionException: java.net.http.WebSocketHandshakeException

**Comment by NikitaMelnikov** [comment]
Странно как, будем разбираться

**Comment by icewind666** [comment]
сейчас заметил что это исключение появляется еще и когда часто перезапускаешь пример. 
то есть остановил - поменял тикер - перезапустил - исключение...
подождал минут 5 - все норм ) 

как будто там коннект старый висит, а второй открыть не дает.

**Comment by NikitaMelnikov** [comment]
Да, так и есть, сейчас ограничение 1 cp-соединение на клиента, мы увеличим лимиты
В SDK при KILL-сигнале, наверно стрим не закрывается

**Comment by zlumyo** [comment]
Стрим не закрывается, поправится в ближайшем релизе

**Comment by NikitaMelnikov** [comment]
> там два раза sandbox!

@orlovk 
Первый sandbox - окружение
Второй sandbox - операции над сендбоксом :)
