### ISSUE TITLE
Несколько тикеров

### ISSUE THREAD

**Issue by icewind666** [TinkoffCreditSystems/invest-openapi-java-sdk#33]
Вопрос - Strategy в SDK задумывалось под работу с одним тикером одновременно?

Я хотел использовать несколько - и было два варианта:

1) Либо запускать несколько StrategyExecutor'ов c разными стратегиями.

2) Либо делать стратегию-сплиттер (которая по тикеру проксирует запросы в другие стратегии). 

Вариант 1 не прокатил - я во всех стратегиях получал одни и те же свечи - то есть все тикеры кидались во все стратегии.

Вариант 2 - тут проблема что, например, в PlacedLimitOrder нету признака (ни figi, ни тикера ).
При этом figi есть в LimitOrder....

**Comment by zlumyo** [comment]
Да, Strategy задумывался под один тикер.
Вы почти нашли верный путь - нужно запускать несколько StrategyExecutor'ов, но на разных подключениях. Тогда каждое подключение будет присылать 1 необходимый тикер.
Однако плодить подключения не очень хорошо, если речь идёт о масштабах больших, чем пара-тройка (сервер имеет свои ограничения). Рассмотрим вариант добавления признака - выглядит, как достаточно простое и эффективное решение.
