### ISSUE TITLE
Работа со стратегией по множеству инструментов

### ISSUE THREAD

**Issue by slavonnet** [TinkoffCreditSystems/invest-openapi-java-sdk#42]
Доброго времени суток.

В Вашем примере все хорошо пока работаем с одним инструментом (и то по по хорошему я надо фильтровать поток в reactOnMarketChange на то, что данный по текущему инструменту 

```
        if (instrumentInfo == null || !instrumentInfo.getFigi().equals(operatingInstrument.getFigi())) {
            return StrategyDecision.pass();
        }

```

А если мне надо запустить стратегию по двум сотням инструментов в портфеле?

Описывать одну стратегию на всех и в ней огромную логику не корректно.
Если запустить для каждого инструмента по стратегии чем-то вида:

```
            final CompletableFuture<Void> result = new CompletableFuture<>();
            List<StrategyExecutor> Ex = new ArrayList<>();
            context.getMarketStocks().join().getInstruments().stream().filter(i -> i.getCurrency() == Currency.RUB).forEach( i -> {
                final var strategy = new SlavonStrategy(i, logger, context);
                final var strategyExecutor = new StrategyExecutor(context, strategy, logger);
                strategyExecutor.run();
                Ex.add(strategyExecutor);
            });
            result.join();

```
то приходится в стратегиях фильтровать огромный поток по инструменту (события идут по всем инструментам, а не по назначенным стратегии).

Возможно тема отдельного тикета, но получить позицию в портфеле из стратегии без передачи туда контекста и запроса getPortfolio вроде как нельзя. Как получить текущую позицию? Срединную стоимость в портфеле? Передача контекста, получение getPortfolio в купе с запуском множества стратегий приводит к гонкам потоков и коллизиям.

Дайте пример как работать в одном приложении с сотнями инструментов сразу, пожалуйста.

**Comment by zlumyo** [comment]
Добрый день! Не первый раз получали подобный вопрос, так что возьмём в разработку в следующем релизе. В первом приближении это будет выглядеть, как возможность указывать несколько стратегий при запуске StrategyExecutor. Внутри будет проксирование потока данных из WebSocket по соответствующим стратегиям.

**Comment by slavonnet** [comment]
А что с получением позиции в портфеле по инструменту внутри стратегии?

**Comment by slavonnet** [comment]
> Внутри будет проксирование потока данных из WebSocket по соответствующим стратегиям.

При проксировании надеюсь будете фильтровать по инструменту. Сейчас в стратегию прилетают события по всем инструментам. Хорошо бы чтобы стратегия была изолирована по событиям по инструменту и не надо было описывать фильтры внутри стратегии. Данную логику  я бы перенес в базовый класс.

**Comment by zlumyo** [comment]
> При проксировании надеюсь будете фильтровать по инструменту. 

Всё правильно - так и будет.

> А что с получением позиции в портфеле по инструменту внутри стратегии?

Это также будет учтено.

**Comment by slavonnet** [comment]
предложил #47 архитектуру изменений, которая на мой взгляд решает множество задач будущего, а главное очень проста и понятна для начинающего разработчика.

**Comment by zlumyo** [comment]
С учётом развития API принято решение об ограничении возможностей предоставляемых SDK. Главным будет поддержание базовых вещей - работа с REST API и Streaming API.
Реализация исполнителей стратегий и другие высокоуровневые вещи пока откладываются.
