### ISSUE TITLE
Caused by: javax.net.ssl.SSLException: No PSK available. Unable to resume.

### ISSUE THREAD

**Issue by slavonnet** [TinkoffCreditSystems/invest-openapi-java-sdk#46]
Через раз подобная ошибка. 

> Caused by: javax.net.ssl.SSLException: No PSK available. Unable to resume.

Указание "-Dhttps.protocols=TLSv1.1,TLSv1.2" не помогает. 
Работаю с песочницей. 
Необходимо в SDK добавить обработку исключения и реконнект.

**Comment by slavonnet** [comment]
Версия JDK была 11.0.1.  При переходе на 13.0.1 вроде пропала. Но обработку эксепшена лучше бы добавить.

**Comment by zlumyo** [comment]
Спасибо за находку! Обработку добавим.

**Comment by zlumyo** [comment]
На данный момент релизация API с использованием стандартного java 11 http-клиента удалена. Если в будущем она вернётся, то описанный здесь момент учётся.
