### ISSUE TITLE
Предложение по архитектуре

### ISSUE THREAD

**Issue by slavonnet** [TinkoffCreditSystems/invest-openapi-java-sdk#47]
Предлагаю ввести следующие понятия в SDK

1. Диспечер (DM). Занимается копированием событий в StrategyManager и получает от StrategyManager информацию о подписках. Скрытый в контексте. Мониторит изменения в подписках StrategyManager. 
2. StrategyManager. Создает копии Стратегий для подключенных инструментов и отправляет им stream с фильтрацией по инструменту. Отправляет изменения по подпискам на Тикеры в Диспетчер.
3. Шаблон стратегии - описание поведения стратегии в рамках некого конкретного Тикера.

Пример Псевдокода

```
StrategyManager <StrategyOne> Manager1 = new StrategyManager<>();
StrategyManager <StrategyTwo> Manager2 = new StrategyManager<>();

Manager1.addTicker("Ticker1");
Manager1.addTicker("Ticker2");
Manager2.addTicker("Ticker2");
Manager2.addTicker("Ticker3");
Manager2.add(Instrument1);


context.addSM(Manager1);
context.addSM(Manager2);


```
Итого происходит подписка на Ticker1 (данные копируются в SM1), Ticker2 (данные копируются в SM1,SM2), Ticker3 (данные копируются в SM2).

Каждый SM как бы по шаблону `<StrategyOne>` создает для каждого Ticker (при add) копию стратегии по шаблону и данные по этому Ticker проксируються в эту стратегию.

Таким образом можно создавать Множество стратегий с Множество различных тикеров в каждом стратегии. При этом Диспечер на верхнем уровне аккумулирует информацию о необходимых подписках и подписывается или отписывается от нужных тикеров. 

Менеджер стратегии получает события от диспетчера и занимается фильтрацией события и проксированием в копию стратегии под данный тиккер.

Шаблон стратегии описывает поведение по T инструменту.  При этом не надо делать return как решение по стратегии. **Не забывайте, что в рамках стратегии может быть множество ордеров сразу.** Лучше дать возможность в момент создания Order указать класс ожидания OrderResult с результатами (ордер по T инструменту установлен, снят, выполнен, отменен, на частичном выполнении). Так будет более универсально и удобно для среднего разработчика.

Внутри шаблона стратегии должна быть возможность "закончить стратегию по инструменту", чтобы SM автоматически остановил стратегию, отписался от событий по ней и удалил копию стратегии по инструменту. Например когда инструмент мы продали и лимитный ордер положительно исполнился мы выполняем команду finish() и SM и Диспечер дальше все сам делает на основе событий.

При addTicker и addSM не забываем выставлять ссылку на context внутрь объекта, для того, чтобы разработчик внутри стратегии имел доступ к глобальным ApiCalls. Также изнутри стратегии надо уметь понимать по какому инструменту идет работа, т.е. при создании копии стратегии в него передается ссылка контекст (может быть null пока SM не добавят в DM) и инструмент.

Программирования среднему джависту на 2-3 дня с тестированием :)

По коду типа того:

```
Class StrategyOne implemets StraregyTempalte {
onPortfolioChange(Portfoilo old, Portfoilo new);
onOrderBookChange(OrderBook old, OrderBook new);
onOrderChange(Order old, Order new);
onInstrumentInfoChange(InstrumentInfo old,InstrumentInfo new);
....
}

Class OrderResult {
onSuccesPost(...);// отправка удалась
onFailedPost(...);// отправка не удалась
onCancelingByUser(...); // в процессе отмены пользователем
onCanceledByUser(...); // снят пользователем
onCanceledBySystem(...); // снят системой
onComplited(...); // исполненный
onPartComplited(...); // частично исполненный
}

```

**Comment by zlumyo** [comment]
Спасибо за такое проработанное предложение!
Пока не подготовил развёрнутый ответ, но уже хотел бы спросить про
> в рамках стратегии может быть множество ордеров сразу

То есть стратегия может при работе с *одним* инструментом выставить несколько ордеров в один момент?

**Comment by slavonnet** [comment]
> Спасибо за такое проработанное предложение!
> Пока не подготовил развёрнутый ответ, но уже хотел бы спросить про
> 
> > в рамках стратегии может быть множество ордеров сразу
> 
> То есть стратегия может при работе с _одним_ инструментом выставить несколько ордеров в один момент?

Конечно. Простой пример лесенка ордеров когда на минус 10 пунктов 1 контракт, минус 20 пунктов 2 контракта и тд

**Comment by zlumyo** [comment]
Точно, не догадался сразу.

**Comment by zlumyo** [comment]
@slavonnet в pull-request, привносящий поддержку java 8, также почти полностью переработана архитектура. Добавлена возможность запуска нескольких стратегий одновременно с разными инструментами в раках одного подключения. Также учтён тот факт, что streaming api (которое по websocket) поддерживает до 6 подключений с одной, что позволяет торговать всеми представленными инструментами одновременно.

**Comment by zlumyo** [comment]
Закрываю тикет по той же причине, что и #42
