### ISSUE TITLE
Совместимость сборки с jitpack.io

### ISSUE THREAD

**Issue by svladykin** [TinkoffCreditSystems/invest-openapi-java-sdk#49]
Сделайте, чтобы сборку можно было забирать с jitpack.io

Сейчас не работает:
https://jitpack.io/com/github/TinkoffCreditSystems/invest-openapi-java-sdk/0.3/build.log

Инструкции:
https://jitpack.io/docs/BUILDING/#gradle-projects
https://jitpack.io/docs/BUILDING/#java-version

**Comment by svladykin** [comment]
https://jitpack.io/#com.github.TinkoffCreditSystems/invest-openapi-java-sdk

**Comment by zlumyo** [comment]
Добавлен файл с настройками JitPack, которые исправляют проблему.
