### ISSUE TITLE
Ошибка при запросе свечи

### ISSUE THREAD

**Issue by tamazyanarsen** [TinkoffCreditSystems/invest-openapi-java-sdk#51]
функция getMarketCandles не работает, выдает ошибку
![image](https://user-images.githubusercontent.com/25464296/69545295-9361cc00-0fa2-11ea-9390-2ba2b7a4707d.png)

**Comment by NikitaMelnikov** [comment]
Привет, 

Можете показать полный адрес запроса после всех преобразований?

**Comment by tamazyanarsen** [comment]
Ошибка была в структуре запроса, временной диапазон был слишком большой
В доках об этом ничего не было
