### ISSUE TITLE
grpc

### ISSUE THREAD

**Issue by ivanantipin** [TinkoffCreditSystems/invest-openapi-java-sdk#52]
сделайте grpc с нормальным стримингом, там все из коробки, ничего клиентского писать вообще не надо, только примеры. сэкономите нервы и бабки и себе и людям

**Comment by NikitaMelnikov** [comment]
Добрый день,

С grpc больше проблем в данный момент, например непонятно как учитывать GOAWAY на клиентах, так как гарантий что GOAWAY будет возвращен для соединения, у которого нет in-flight запросов, нет

**Comment by ivanantipin** [comment]
не совсем понял то, что описано с GOAWAY,  используем плотно grpc, все работает отлично на больших объемах и с передподключениями. Я знаю более серьезные проекты, типа cockroachdb, используют тот же протокол, так что сказки все это про много проблем. может пару лет назад было, но все основное уже зафиксано. так бы и сказали что замазались с openapi теперь переписывать дорого. понаписали много на клиентской части, еще будете десять раз переделывать, когда можно было обойтись котрактом и примерами

**Comment by NikitaMelnikov** [comment]
При работает node <-> node проблем не возникает, как в случае с cockroachdb, например.
Проблемы возникают на балансерах
