### ISSUE TITLE
jdk11-ssl issue

### ISSUE THREAD

**Issue by ivanantipin** [TinkoffCreditSystems/invest-openapi-java-sdk#53]
reproduced with:
linux - jdk 11

after 2 mins run of demo App 
got hight cpu (200%) + stop recieving messages from websocket

profiler shows native jdk network stack takes cpu

fixed after updating to jdk 13 

seems that related to

https://stackoverflow.com/questions/54485755/java-11-httpclient-leads-to-endless-ssl-loop

**Comment by ivanantipin** [comment]
seems similar to https://github.com/TinkoffCreditSystems/invest-openapi-java-sdk/issues/46

**Comment by zlumyo** [comment]
Closing due duplicating #46
