### ISSUE TITLE
executedPrice  в PlacedLimitOrder

### ISSUE THREAD

**Issue by ivanantipin** [TinkoffCreditSystems/invest-openapi-java-sdk#54]
нужна цена executedPrice в  PlacedLimitOrder
тк он содержит executedLots
из портфеля вытаскивать среднюю цену неудобно
цена лимитного ордера часто другая чем executed

**Comment by zlumyo** [comment]
Этот вопрос относится скорее к самому API, чем к SDK. Задайте его в [соответствующем репозитории](https://github.com/TinkoffCreditSystems/invest-openapi)
