### ISSUE TITLE
averagePositionPrice = null in portfolio

### ISSUE THREAD

**Issue by ivanantipin** [TinkoffCreditSystems/invest-openapi-java-sdk#55]
position Portfolio{positions=[PortfolioPosition{figi='BBG004730N88', ticker='SBER', isin='RU0009029540', instrumentType=Stock, balance=160.0, blocked=0, expectedYield=null, lots=16, averagePositionPrice=null, averagePositionPriceNoNkd=null}]}

**Comment by zlumyo** [comment]
According to API documentation `averagePostionPrice` is optional field, so in Java it can be null.
