### ISSUE TITLE
Непонятный ответ /market/orderbook (облигации)

### ISSUE THREAD

**Issue by yakuhin** [TinkoffCreditSystems/invest-openapi-java-sdk#59]
Метод /market/orderbook  возвращает непонятные цены (lastPrice, closePrice) по облигациям (цена/10):
Например: 
'BBG00PYL6030' (Белуга Групп)
/market/bonds
{'figi': 'BBG00PYL6030', 'ticker': 'RU000A100L63', 'isin': 'RU000A100L63', 'minPriceIncrement': 0.01, 'lot': 1, 'currency': 'RUB', 'name': 'Белуга Групп выпуск 1'}
/market/orderbook  
{'figi': 'BBG00PYL6030', 'depth': 5, 'tradeStatus': 'NotAvailableForTrading', 'minPriceIncrement': 0.01, 'lastPrice': 105.47, 'closePrice': 105.47, 'bids': [], 'asks': []}
 Хотя в терминале
![image](https://user-images.githubusercontent.com/48122336/71339381-5585a280-2564-11ea-88bc-c7000509c1a3.png)

Непонятно почему 'lastPrice' = Цена/10
Также непонятно, как выйти на стоимость отображаемую в терминале и мобильном приложении

Аналогичная ситуация и по остальным облигациям

**Comment by NikitaMelnikov** [comment]
Добрый день, такое поведение не только в java-sdk, это связано с подсчетом стоимости облигаций на OpenApi. Дело в том, что мы отображаем не фактическую цену, а некоторый процент от цены, это баг, который мы поправим в начале следующего года.

Предлагаю создать тикет в основном репозитории https://github.com/TinkoffCreditSystems/invest-openapi/issues и этот закрыть
