### ISSUE TITLE
Не соответствующие аннотации @NotNull

### ISSUE THREAD

**Issue by Vitek000** [TinkoffCreditSystems/invest-openapi-java-sdk#64]
1. Метод OperationsContext.getOperations
параметр figi может быть null, так как есть возможность получать все операции
2. Класс Instrument
....
//                      @JsonProperty(value = "type", required = true)
                      @JsonProperty(value = "type") // MY CHANGE!!! This property is not obligatory for some reason!!!
                      @NotNull
                      final InstrumentType type
....
Например, если я получаю InstrumentList по методу marketContext.getMarketStocks() то приходит в респонсе intrumentList.instrument[i].type = null

**Comment by zlumyo** [comment]
Пункт 1 был исправлен.
Пункт 2 является следствием ошибки в самом API, которое перестало возвращать поле `type`.
