### ISSUE TITLE
Отсутствуют типы операций

### ISSUE THREAD

**Issue by Vitek000** [TinkoffCreditSystems/invest-openapi-java-sdk#65]
ru.tinkoff.invest.openapi.models.operations.OperationType
Надо добавить
    @JsonProperty("TaxBack")
    TaxBack,
    @JsonProperty("Tax")
    Tax,

**Comment by zlumyo** [comment]
Оказывается там больше недостающих типов.

**Comment by Vitek000** [comment]
Это те недостающие типы, с которыми я столкнулся на своем аккаунте :)
