### ISSUE TITLE
Активные заявки по валюте не возвращаются.

### ISSUE THREAD

**Issue by niksmet** [TinkoffCreditSystems/invest-openapi-java-sdk#84]
Метод `OrdersContext.getOrders(String brokerAccountId)` не возвращает список активных заявок по валюте.
Воспроизводство:
1. Создаем лимитный ордер на покупку $1к за 70 рублей
2. OrdersContext.getOrders() возвращает пустой список.

**Comment by zlumyo** [comment]
Это воспроизводится при "ручном" выполнении REST-методов, например, через [swagger](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/)?

**Comment by niksmet** [comment]
Да, легко повторяется вот здесь: https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/

**Comment by zlumyo** [comment]
Если это воспроизводится на чистых REST-вызовах, то это уже не тема SDK. Такой вопрос необходимо задать в [репозитории Open API](https://github.com/TinkoffCreditSystems/invest-openapi).
