### ISSUE TITLE
Опубликовать SDK в Maven

### ISSUE THREAD

**Issue by xkrt** [TinkoffCreditSystems/invest-openapi-java-sdk#9]
Привет,

Опубликуйте пожалуйста SDK на https://mvnrepository.com/artifact/ru.tinkoff для удобства подключения его к своему проекту.

**Comment by NikitaMelnikov** [comment]
Привет, мы в процессе, ждем подтверждения что мы тоже `ru.tinkoff` :)

**Comment by xkrt** [comment]
Привет, было бы удобнее отслеживать прогресс, если вы бы закрыли заявку когда фактически SDK будет опубликован в  репозиторий.

**Comment by svladykin** [comment]
попробовал использовать jitpack.io вместо мавен централа, не работает #49

**Comment by xkrt** [comment]
+ не забудьте пожалуйста выложить source jar туда же для удобства использования из IDE

**Comment by ogronome** [comment]
Добрый день. Уже полгода прошло. Всё ещё "ждем подтверждения"? 8-\

**Comment by NikitaMelnikov** [comment]
@zlumyo как продвигается?

**Comment by zlumyo** [comment]
Опубликуем с релизом с релизом 0.4, который "скоро" случится.

**Comment by zlumyo** [comment]
Вышел релиз 0.4. Он опубликован в Центральный репозиторий https://repo1.maven.org/maven2/ru/tinkoff/invest/
