### ISSUE TITLE
OrderSubscribeRequest - хотелось бы иметь такую возможность

### ISSUE THREAD

**Issue by malltshik** [TinkoffCreditSystems/invest-openapi-java-sdk#90]
OrderSubscribeRequest 
OrderUnsubscribeRequest 

Две сущности для подписки на состояние заявки для реализации операций с временем выполнения.
Например: купить 1 лот тинькофф по рыночной цене в течении 10 секунд.

**Comment by zlumyo** [comment]
На данные момент само API не предоставляет подобной функциональности. Пока что мы делаем SDK только, как прямую реализацию возможностей API. Если нужно что-то сверху того, то в ваших руках реализовать это самостоятельно.
Если вы хотите, чтобы API непосредственно предоставляло такую воможность (которая, разумеется, будет отражена в SDK), то можете запросить это [в его репозитории](https://github.com/TinkoffCreditSystems/invest-openapi/issues).
