### ISSUE TITLE
Добавить возможность указания clientIndex в sendRequest

### ISSUE THREAD

**Issue by accedx** [TinkoffCreditSystems/invest-openapi-java-sdk#92]
В функции

`public void sendRequest(@NotNull final StreamingRequest request)`

clientIndex вычисляется следующим образом

`final int clientIndex = request.hashCode() % this.wsClients.length;`

таким образом вероятность успешного unsubscribe стремится к нулю, т. к. hashCode экземпляров класса OrderbookSubscribeRequest и OrderbookUnsubscribeRequest (как пример) различен и следовательно отправятся через разные клиенты.
```
api.streamingContext.sendRequest(StreamingRequest.subscribeOrderbook(figi, depth))
api.streamingContext.sendRequest(StreamingRequest.unsubscribeOrderbook(figi, depth))
```

Предлагаю добавить к функции sendRequest параметр clientIndex, либо вместо использования hashCode экземпляра класса StreamingRequest использовать hash от результата функции onOffPairId().

**Comment by zlumyo** [comment]
Остановимся на варианте с использованием hash от результата функции onOffPairId().
