### ISSUE TITLE
Критика core

### ISSUE THREAD

**Issue by newmen** [TinkoffCreditSystems/invest-openapi-java-sdk#93]
Здравствуйте! Я глубоко уважаю вас и ваш труд, но по мере ознакомления с вашим чудным SDK, у меня накопилось несколько недоумений, которые, с вашего позволения, опишу тут. Все негодования будут относительно core, поскольку это всё таки core, и именно оно подразумевает расширения и реализацию поверх него кастомерской логики.

1. Совершенно не понятно зачем вы рукой написали так много всего в models? Ведь давно уже есть такой проект как [JsonSchema](https://json-schema.org) и автогенерация с помощью [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo) джавийных классиков, на основании её. Таковое описание публичного интерфейса гораздо более выгодно, поскольку схему можно использовать не только в джавийном коде, но и в других языках. Да и поддерживать это проще. С другой стороны, с JsonSchema есть ряд не решённых проблем, на уровне стандарта. Но на мой взгляд, это не повод отказываться от столь унифицированной штуки. Тем более, что в выше упомянутой jsonschema2pojo некоторые из них уже порешали.
2. У вас два одинаковых `InstrumentType` в market и portfolio.
3. Модели `EmptyPayload`, `ErrorPayload` и `RestResponse` выбиваются из стройного ряда остальных моделей. А раз так, то их следовало бы положить отдельно.
4. Вы везде маниакально используете аннотацию `@NotNull`. В целом, аннотация безусловно годная, но зачем ею всё аннотировать, если можно объявить `@NotNull` на уровне пэкейджа, и тогда всё по дефолту будет NotNull. Например вот так:
```
package ru.tinkoff.utils;

// imports...

@Documented
@NotNull
@TypeQualifierDefault({
        ElementType.ANNOTATION_TYPE,
        ElementType.CONSTRUCTOR,
        ElementType.FIELD,
        ElementType.LOCAL_VARIABLE,
        ElementType.METHOD,
        ElementType.PACKAGE,
        ElementType.PARAMETER,
        ElementType.TYPE
})
@Retention(RetentionPolicy.RUNTIME)
public @interface NotNullByDefault {
}
```
```
@NotNullByDefault
package ru.tinkoff.invest.openapi;

import ru.tinkoff.utils.NotNullByDefault;
```
5. Класс OpenApiFactoryBase – просто мрак.
- На кой чёрт делать его зависимым от `java.util.logging.Logger`? Да, это безусловно стандарт, но ведь ваш SDK для джавы! А в джаве есть целая тонна всяких разых логгеров, и, к сожалению, а может и к счастью, стандартный логгер – не самый популярный. Разве нельзя было просто выбрасывать эксепшин?
- Как по мне, так очень странно передавать экзекьютора в методы получения OpenApi клиентов. Зачем? Почему нельзя было выставить абстрактые методы без аргументов? А уже всякая реализация этой фабрики сама бы заботилась о том где брать `Executor`.

**Comment by newmen** [comment]
Ох, обнаружил у вас таки swagger. Но в таком случае почему было не прикрутить автогенерацию модельных классов на основании него? Зачем подкладывать нагенерённые файлы?

**Comment by leodev87** [comment]
Согласен с автором ваш core это ппц.. особенно вшитый логгер...

**Comment by zlumyo** [comment]
В прилинкованном ПР постарался устранить замечения и иные огрехи. Единственное, с анннотациями `@NotNull` оставил как есть - для гарантии kotlin-совместимого интерфейса. Если делать на уровне пакета, то есть шанс чего-то лишнего зацепить.
