### ISSUE TITLE
Ошибка запроса свечей по несуществующему figi

### ISSUE THREAD

**Issue by HE-ff** [TinkoffCreditSystems/invest-openapi-java-sdk#95]
При запросе свечей по несуществующему figi  должен возвращаться пустой список, как это реализовано  в

`ru.tinkoff.invest.openapi.okhttp.MarketContextImpl#getMarketCandles`

Ожидается, что сервер вернет код ошибки

`INSTRUMENT_ERROR`

однако он возвращает

`ErrorPayload(message='[figi]: Instrument not found by figi=BB445645547456', code='VALIDATION_ERROR')`

Поэтому метод выбрасывает исключение вместо пустого списка.

**Comment by NikitaMelnikov** [comment]
Поиск по FIGI возвращает не список, а конкретный инструмент
