### ISSUE TITLE
PortfolioPosition возвращает количество акций на балансе в двух филдах 

### ISSUE THREAD

**Issue by ityulkanov** [TinkoffCreditSystems/invest-openapi-java-sdk#97]
Я ожидаю что lots должны возвращать количество лотов, а balance количество лотов * на последнюю цену. 
Сейчас по запросу .balance выдает то же что и .lots
Получаю positions через api.getPortfolioContext().getPortfolio(brokerId).get().positions

**Comment by lightning95** [comment]
Такой же ли ответ при вызове сваггера?

**Comment by lightning95** [comment]
Какие lots / balance для доллара?

**Comment by ityulkanov** [comment]
![image](https://user-images.githubusercontent.com/998653/82176721-3bb47580-98e0-11ea-88e3-4f3b0dd37de8.png)

**Comment by ityulkanov** [comment]
![image](https://user-images.githubusercontent.com/998653/82177147-6d7a0c00-98e1-11ea-8cc8-199e23204f68.png)

**Comment by ityulkanov** [comment]
Насчет сваггера не знаю, как его вызвать?

**Comment by lightning95** [comment]
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/

**Comment by ityulkanov** [comment]
Да, в сваггере везде lots == balance

**Comment by lightning95** [comment]
Итак, `lots` -  количество лотов в позиции
`balance` - количество единиц позиций
например, 
```
lotSize(USD) = 1000
balance (USD) = 1234
lots(USD) = 1
```

**Comment by lightning95** [comment]
скорее всего вы хотите `currentPositionPrice`, как аналогия для `averagePositionPrice`?
тогда не проще ли самому поддерживать текущую стоимость позиции по ценам из стрима?

**Comment by ityulkanov** [comment]
Да, я себе уже реализовал что то подобное. Просто не очень понял что к чему сразу. Ну и ожидал, все же чего-то простого для получения текущей стоимости позиции.
